// Transcript program display + edit view

import SwiftUI

struct TranscriptProgramView: View {
  @EnvironmentObject var appState: AppState
  let transcriptId: UUID

  /// Local working copy — saved back on disappear.
  @State private var program: TranscriptProgram

  init(transcriptId: UUID, program: TranscriptProgram) {
    self.transcriptId = transcriptId
    self._program = State(initialValue: program)
  }

  var body: some View {
    List {
      // Key Points
      editableSection(
        title: "Key Points",
        icon: "lightbulb",
        tint: Theme.keyPoints,
        items: $program.keyPoints
      )

      // Study Tasks
      editableSection(
        title: "Study Tasks",
        icon: "checklist",
        tint: Theme.studyTasks,
        items: $program.studyTasks
      )

      // Quiz Questions
      editableSection(
        title: "Quiz Questions",
        icon: "questionmark.circle",
        tint: Theme.quiz,
        items: $program.quizQuestions
      )

      // Footer
      Section {
        Text("Generated \(program.generatedAt.formatted(date: .abbreviated, time: .shortened))")
          .font(.caption)
          .foregroundStyle(.tertiary)
      }
    }
    .listStyle(.insetGrouped)
    .navigationTitle("Program")
    .navigationBarTitleDisplayMode(.inline)
    .toolbar {
      ToolbarItem(placement: .topBarTrailing) {
        Image(systemName: "person.crop.circle")
          .foregroundStyle(Theme.accent)
      }
      ToolbarItem(placement: .topBarTrailing) {
        ShareLink(item: generateShareText()) {
          Image(systemName: "square.and.arrow.up")
        }
      }
      ToolbarItem(placement: .topBarTrailing) {
        EditButton()
      }
    }
    .onDisappear {
      appState.updateProgram(for: transcriptId, program: program)
    }
  }

  private func generateShareText() -> String {
    var text = "Study Program: \(program.generatedAt.formatted(date: .abbreviated, time: .shortened))\n\n"
    
    text += "## Key Points\n"
    for (i, p) in program.keyPoints.enumerated() { text += "\(i+1). \(p)\n" }
    text += "\n"
    
    text += "## Study Tasks\n"
    for (i, t) in program.studyTasks.enumerated() { text += "\(i+1). \(t)\n" }
    text += "\n"
    
    text += "## Quiz Questions\n"
    for (i, q) in program.quizQuestions.enumerated() { text += "\(i+1). \(q)\n" }
    
    text += "\nGenerated by Trapp"
    return text
  }

  @ViewBuilder
  private func editableSection(title: String, icon: String, tint: Color, items: Binding<[String]>) -> some View {
    Section {
      if items.wrappedValue.isEmpty {
        Text("No items — tap + to add one.")
          .font(.subheadline)
          .foregroundStyle(.secondary)
          .italic()
      } else {
        ForEach(items.wrappedValue.indices, id: \.self) { index in
          TextField(title, text: items[index], axis: .vertical)
            .font(.subheadline)
            .lineLimit(1...5)
        }
        .onDelete { offsets in
          withAnimation {
            var updated = items.wrappedValue
            updated.remove(atOffsets: offsets)
            items.wrappedValue = updated
          }
          HapticManager.shared.play(.light)
        }
        .onMove { source, destination in
          withAnimation {
            var updated = items.wrappedValue
            updated.move(fromOffsets: source, toOffset: destination)
            items.wrappedValue = updated
          }
          HapticManager.shared.play(.light)
        }
      }

      Button {
        withAnimation {
          items.wrappedValue.append("")
        }
        HapticManager.shared.play(.light)
      } label: {
        Label("Add", systemImage: "plus.circle")
          .font(.subheadline)
          .foregroundStyle(tint)
      }
    } header: {
      Label(title, systemImage: icon)
        .font(.headline)
        .foregroundStyle(tint)
        .textCase(nil)
    }
  }
}
